### get all staffs
GET http://localhost:3000

### get a staff by id
GET http://localhost:3000/edit/1

### create a staff
POST http://localhost:3000/create
Content-Type: application/json

{
    "StaffName": "Thein Htet Oo",
    "StaffCode": "SCM-2022"
}

### update a staff
PATCH http://localhost:3000/update/1
Content-Type: application/json

{
    "StaffName": "Lee Min Ho"
}

### delete a staff
DELETE http://localhost:3000/delete/1
